Vagrant.configure(2) do |config|
  config.vm.box = "fedora/25-cloud-base"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 3000, host:3000 
  config.ssh.insert_key=false
  
  #config.vm.network "private_network",  ip: "192.168.10.155"

  #config.vm.synced_folder "../src", "/vagrant"
  
  config.vm.provider "virtualbox" do |vb|
	#vb.gui = true
	#vb.memory = "1024"
  end
end
