Vagrant.configure(2) do |config|
  config.vm.box = "polyakov/docker-k8s-build"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 3000, host:3000 
  config.ssh.insert_key=false
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
