kubectl delete service "mongo1-svc"
kubectl delete service "mongo2-svc"
kubectl delete service "arbiter-svc"
kubectl delete service app-api-svc
kubectl delete service www-svc
kubectl delete rc "arbiter-rc"
kubectl delete rc "app-rc"
kubectl delete rc "www-rc"
kubectl delete po "mongo-db1"
kubectl delete po "mongo-db2"
